//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Benutzer", Namespace="http://schemas.datacontract.org/2004/07/ProjektarbeitVokabeltrainerServer")]
    [System.SerializableAttribute()]
    public partial class Benutzer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Fach Fach1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Fach Fach2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Fach Fach3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Fach Fach4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Teststatistik StatistikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Fach Fach1 {
            get {
                return this.Fach1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Fach1Field, value) != true)) {
                    this.Fach1Field = value;
                    this.RaisePropertyChanged("Fach1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Fach Fach2 {
            get {
                return this.Fach2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Fach2Field, value) != true)) {
                    this.Fach2Field = value;
                    this.RaisePropertyChanged("Fach2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Fach Fach3 {
            get {
                return this.Fach3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Fach3Field, value) != true)) {
                    this.Fach3Field = value;
                    this.RaisePropertyChanged("Fach3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Fach Fach4 {
            get {
                return this.Fach4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Fach4Field, value) != true)) {
                    this.Fach4Field = value;
                    this.RaisePropertyChanged("Fach4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Passwort {
            get {
                return this.PasswortField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswortField, value) != true)) {
                    this.PasswortField = value;
                    this.RaisePropertyChanged("Passwort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Teststatistik Statistik {
            get {
                return this.StatistikField;
            }
            set {
                if ((object.ReferenceEquals(this.StatistikField, value) != true)) {
                    this.StatistikField = value;
                    this.RaisePropertyChanged("Statistik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fach", Namespace="http://schemas.datacontract.org/2004/07/ProjektarbeitVokabeltrainerServer")]
    [System.SerializableAttribute()]
    public partial class Fach : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZeitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zeit {
            get {
                return this.ZeitField;
            }
            set {
                if ((object.ReferenceEquals(this.ZeitField, value) != true)) {
                    this.ZeitField = value;
                    this.RaisePropertyChanged("Zeit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Teststatistik", Namespace="http://schemas.datacontract.org/2004/07/ProjektarbeitVokabeltrainerServer")]
    [System.SerializableAttribute()]
    public partial class Teststatistik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TestBeendetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TestGestartetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VokabelGeübtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VokabelRichtigField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TestBeendet {
            get {
                return this.TestBeendetField;
            }
            set {
                if ((this.TestBeendetField.Equals(value) != true)) {
                    this.TestBeendetField = value;
                    this.RaisePropertyChanged("TestBeendet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TestGestartet {
            get {
                return this.TestGestartetField;
            }
            set {
                if ((this.TestGestartetField.Equals(value) != true)) {
                    this.TestGestartetField = value;
                    this.RaisePropertyChanged("TestGestartet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VokabelGeübt {
            get {
                return this.VokabelGeübtField;
            }
            set {
                if ((this.VokabelGeübtField.Equals(value) != true)) {
                    this.VokabelGeübtField = value;
                    this.RaisePropertyChanged("VokabelGeübt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VokabelRichtig {
            get {
                return this.VokabelRichtigField;
            }
            set {
                if ((this.VokabelRichtigField.Equals(value) != true)) {
                    this.VokabelRichtigField = value;
                    this.RaisePropertyChanged("VokabelRichtig");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vokabel", Namespace="http://schemas.datacontract.org/2004/07/ProjektarbeitVokabeltrainerServer")]
    [System.SerializableAttribute()]
    public partial class Vokabel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BenutzerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeutschField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Deutsch2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnglischField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Englisch2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FachField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BenutzerId {
            get {
                return this.BenutzerIdField;
            }
            set {
                if ((this.BenutzerIdField.Equals(value) != true)) {
                    this.BenutzerIdField = value;
                    this.RaisePropertyChanged("BenutzerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Deutsch {
            get {
                return this.DeutschField;
            }
            set {
                if ((object.ReferenceEquals(this.DeutschField, value) != true)) {
                    this.DeutschField = value;
                    this.RaisePropertyChanged("Deutsch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Deutsch2 {
            get {
                return this.Deutsch2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Deutsch2Field, value) != true)) {
                    this.Deutsch2Field = value;
                    this.RaisePropertyChanged("Deutsch2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Englisch {
            get {
                return this.EnglischField;
            }
            set {
                if ((object.ReferenceEquals(this.EnglischField, value) != true)) {
                    this.EnglischField = value;
                    this.RaisePropertyChanged("Englisch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Englisch2 {
            get {
                return this.Englisch2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Englisch2Field, value) != true)) {
                    this.Englisch2Field = value;
                    this.RaisePropertyChanged("Englisch2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fach {
            get {
                return this.FachField;
            }
            set {
                if ((this.FachField.Equals(value) != true)) {
                    this.FachField = value;
                    this.RaisePropertyChanged("Fach");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProjektarbeitVokabeltrainerServer.IProjektarbeitVokabeltrainerServer")]
    public interface IProjektarbeitVokabeltrainerServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/Registrieren", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/RegistrierenResponse")]
        bool Registrieren(ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Benutzer benutzer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/Registrieren", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/RegistrierenResponse")]
        System.Threading.Tasks.Task<bool> RegistrierenAsync(ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Benutzer benutzer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/Anmelden", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/AnmeldenResponse")]
        ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Benutzer Anmelden(string benutzerid, ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Benutzer benutzer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/Anmelden", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/AnmeldenResponse")]
        System.Threading.Tasks.Task<ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Benutzer> AnmeldenAsync(string benutzerid, ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Benutzer benutzer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetBenutzer", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetBenutzerResponse")]
        ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Benutzer GetBenutzer(string benutzerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetBenutzer", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetBenutzerResponse")]
        System.Threading.Tasks.Task<ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Benutzer> GetBenutzerAsync(string benutzerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetAllBenutzer", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetAllBenutzerResponse")]
        ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Benutzer[] GetAllBenutzer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetAllBenutzer", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetAllBenutzerResponse")]
        System.Threading.Tasks.Task<ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Benutzer[]> GetAllBenutzerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/CreateVokabel", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/CreateVokabelResponse")]
        bool CreateVokabel(ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel vokabel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/CreateVokabel", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/CreateVokabelResponse")]
        System.Threading.Tasks.Task<bool> CreateVokabelAsync(ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel vokabel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/UpdateVokabel", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/UpdateVokabelResponse")]
        bool UpdateVokabel(string vokabelid, ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel vokabel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/UpdateVokabel", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/UpdateVokabelResponse")]
        System.Threading.Tasks.Task<bool> UpdateVokabelAsync(string vokabelid, ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel vokabel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/UpdateVokabelList", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/UpdateVokabelListResponse")]
        bool UpdateVokabelList(ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel[] vokabel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/UpdateVokabelList", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/UpdateVokabelListResponse")]
        System.Threading.Tasks.Task<bool> UpdateVokabelListAsync(ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel[] vokabel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/DeleteVokabel", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/DeleteVokabelResponse")]
        bool DeleteVokabel(string vokabelid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/DeleteVokabel", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/DeleteVokabelResponse")]
        System.Threading.Tasks.Task<bool> DeleteVokabelAsync(string vokabelid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetVokabel", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetVokabelResponse")]
        ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel GetVokabel(string vokabelid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetVokabel", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetVokabelResponse")]
        System.Threading.Tasks.Task<ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel> GetVokabelAsync(string vokabelid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetVokabelForBenutzer", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetVokabelForBenutzerRespon" +
            "se")]
        ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel[] GetVokabelForBenutzer(string benutzerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetVokabelForBenutzer", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetVokabelForBenutzerRespon" +
            "se")]
        System.Threading.Tasks.Task<ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel[]> GetVokabelForBenutzerAsync(string benutzerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetVokabelForBenutzerForFac" +
            "h", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetVokabelForBenutzerForFac" +
            "hResponse")]
        ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel[] GetVokabelForBenutzerForFach(string benutzerid, string vokabelFach);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetVokabelForBenutzerForFac" +
            "h", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetVokabelForBenutzerForFac" +
            "hResponse")]
        System.Threading.Tasks.Task<ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel[]> GetVokabelForBenutzerForFachAsync(string benutzerid, string vokabelFach);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetFächer", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetFächerResponse")]
        ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Fach[] GetFächer(string benutzerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetFächer", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetFächerResponse")]
        System.Threading.Tasks.Task<ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Fach[]> GetFächerAsync(string benutzerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/UpdateFach", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/UpdateFachResponse")]
        bool UpdateFach(string benutzerid, ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Fach fach);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/UpdateFach", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/UpdateFachResponse")]
        System.Threading.Tasks.Task<bool> UpdateFachAsync(string benutzerid, ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Fach fach);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetStatistik", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetStatistikResponse")]
        ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Teststatistik GetStatistik(string benutzerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetStatistik", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/GetStatistikResponse")]
        System.Threading.Tasks.Task<ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Teststatistik> GetStatistikAsync(string benutzerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/UpdateStatistik", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/UpdateStatistikResponse")]
        bool UpdateStatistik(string benutzerid, ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Teststatistik statistik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjektarbeitVokabeltrainerServer/UpdateStatistik", ReplyAction="http://tempuri.org/IProjektarbeitVokabeltrainerServer/UpdateStatistikResponse")]
        System.Threading.Tasks.Task<bool> UpdateStatistikAsync(string benutzerid, ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Teststatistik statistik);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProjektarbeitVokabeltrainerServerChannel : ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.IProjektarbeitVokabeltrainerServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjektarbeitVokabeltrainerServerClient : System.ServiceModel.ClientBase<ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.IProjektarbeitVokabeltrainerServer>, ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.IProjektarbeitVokabeltrainerServer {
        
        public ProjektarbeitVokabeltrainerServerClient() {
        }
        
        public ProjektarbeitVokabeltrainerServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjektarbeitVokabeltrainerServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjektarbeitVokabeltrainerServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjektarbeitVokabeltrainerServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Registrieren(ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Benutzer benutzer) {
            return base.Channel.Registrieren(benutzer);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrierenAsync(ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Benutzer benutzer) {
            return base.Channel.RegistrierenAsync(benutzer);
        }
        
        public ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Benutzer Anmelden(string benutzerid, ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Benutzer benutzer) {
            return base.Channel.Anmelden(benutzerid, benutzer);
        }
        
        public System.Threading.Tasks.Task<ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Benutzer> AnmeldenAsync(string benutzerid, ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Benutzer benutzer) {
            return base.Channel.AnmeldenAsync(benutzerid, benutzer);
        }
        
        public ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Benutzer GetBenutzer(string benutzerid) {
            return base.Channel.GetBenutzer(benutzerid);
        }
        
        public System.Threading.Tasks.Task<ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Benutzer> GetBenutzerAsync(string benutzerid) {
            return base.Channel.GetBenutzerAsync(benutzerid);
        }
        
        public ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Benutzer[] GetAllBenutzer() {
            return base.Channel.GetAllBenutzer();
        }
        
        public System.Threading.Tasks.Task<ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Benutzer[]> GetAllBenutzerAsync() {
            return base.Channel.GetAllBenutzerAsync();
        }
        
        public bool CreateVokabel(ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel vokabel) {
            return base.Channel.CreateVokabel(vokabel);
        }
        
        public System.Threading.Tasks.Task<bool> CreateVokabelAsync(ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel vokabel) {
            return base.Channel.CreateVokabelAsync(vokabel);
        }
        
        public bool UpdateVokabel(string vokabelid, ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel vokabel) {
            return base.Channel.UpdateVokabel(vokabelid, vokabel);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateVokabelAsync(string vokabelid, ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel vokabel) {
            return base.Channel.UpdateVokabelAsync(vokabelid, vokabel);
        }
        
        public bool UpdateVokabelList(ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel[] vokabel) {
            return base.Channel.UpdateVokabelList(vokabel);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateVokabelListAsync(ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel[] vokabel) {
            return base.Channel.UpdateVokabelListAsync(vokabel);
        }
        
        public bool DeleteVokabel(string vokabelid) {
            return base.Channel.DeleteVokabel(vokabelid);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteVokabelAsync(string vokabelid) {
            return base.Channel.DeleteVokabelAsync(vokabelid);
        }
        
        public ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel GetVokabel(string vokabelid) {
            return base.Channel.GetVokabel(vokabelid);
        }
        
        public System.Threading.Tasks.Task<ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel> GetVokabelAsync(string vokabelid) {
            return base.Channel.GetVokabelAsync(vokabelid);
        }
        
        public ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel[] GetVokabelForBenutzer(string benutzerid) {
            return base.Channel.GetVokabelForBenutzer(benutzerid);
        }
        
        public System.Threading.Tasks.Task<ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel[]> GetVokabelForBenutzerAsync(string benutzerid) {
            return base.Channel.GetVokabelForBenutzerAsync(benutzerid);
        }
        
        public ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel[] GetVokabelForBenutzerForFach(string benutzerid, string vokabelFach) {
            return base.Channel.GetVokabelForBenutzerForFach(benutzerid, vokabelFach);
        }
        
        public System.Threading.Tasks.Task<ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Vokabel[]> GetVokabelForBenutzerForFachAsync(string benutzerid, string vokabelFach) {
            return base.Channel.GetVokabelForBenutzerForFachAsync(benutzerid, vokabelFach);
        }
        
        public ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Fach[] GetFächer(string benutzerid) {
            return base.Channel.GetFächer(benutzerid);
        }
        
        public System.Threading.Tasks.Task<ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Fach[]> GetFächerAsync(string benutzerid) {
            return base.Channel.GetFächerAsync(benutzerid);
        }
        
        public bool UpdateFach(string benutzerid, ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Fach fach) {
            return base.Channel.UpdateFach(benutzerid, fach);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateFachAsync(string benutzerid, ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Fach fach) {
            return base.Channel.UpdateFachAsync(benutzerid, fach);
        }
        
        public ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Teststatistik GetStatistik(string benutzerid) {
            return base.Channel.GetStatistik(benutzerid);
        }
        
        public System.Threading.Tasks.Task<ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Teststatistik> GetStatistikAsync(string benutzerid) {
            return base.Channel.GetStatistikAsync(benutzerid);
        }
        
        public bool UpdateStatistik(string benutzerid, ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Teststatistik statistik) {
            return base.Channel.UpdateStatistik(benutzerid, statistik);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateStatistikAsync(string benutzerid, ProjektarbeitVokabeltrainer.ProjektarbeitVokabeltrainerServer.Teststatistik statistik) {
            return base.Channel.UpdateStatistikAsync(benutzerid, statistik);
        }
    }
}
